<?php

namespace Addons\Studymaterial\Model;
use Think\Model;

/**
 * Studymaterial模型
 */
class WxyStudyMaterialModel extends Model{
    public function table($table)
    {
        return parent::table($table); // TODO: Change the autogenerated stub
    }

}
